name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Check formatting
        run: mise run fmt

      - name: Lint
        run: mise run lint
