name: Test

on:
  workflow_call:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Build
        run: mise run build

      - name: Run tests
        run: mise run test
